EXTRA_CFLAGS += -DDEBUG
obj-m   += snd-soc-nau8824.o
obj-m  += snd-soc-sst-cht-bsw-nau8824.o
obj-m  += snd-soc-acpi-intel-match.o

snd-soc-nau8824-objs := nau8824.o
snd-soc-sst-cht-bsw-nau8824-objs := cht_bsw_nau8824.o
snd-soc-acpi-intel-match-objs := soc-acpi-intel-byt-match.o soc-acpi-intel-cht-match.o soc-acpi-intel-hsw-bdw-match.o

